package goRPC

import (
	"encoding/json"
	//"fmt"
)


type AutoGenerated struct {
	Ub1 struct {
		Sub1 struct {
			A int    `json:"a"`
			B string `json:"b"`
			C struct {
				Q int `json:"q"`
				W int `json:"w"`
			} `json:"c"`
		} `json:"sub1"`
	} `json:"ub1"`
}


func JsonLoads(src string, dst *interface{}) (error) {
	err := json.Unmarshal([]byte(src), dst)
	return err
}


func (dst *AutoGenerated) JsonLoadsStruct(src string) (error) {
	err := json.Unmarshal([]byte(src), dst)
	return err
}


func JsonDumps(src interface{}) (string, error) {
	var err 	error
	var dstByte []byte

	if dstByte, err = json.Marshal(src); err == nil {
		return string(dstByte), err
	}
	return "", err
}